### ISSUE TITLE
MELPA?

### ISSUE THREAD

**Issue by manuel-uberti** [joostkremers/nswbuff#1]
Not an issue, just a question: any chance you can release this on MELPA?

I've been trying it out in the last few days, and it's really a great add to my config.

**Comment by joostkremers** [comment]
I've opened  pull request just now: https://github.com/melpa/melpa/pull/6005.

Since most of the code isn't mine, I wasn't sure if Melpa would include it, but now that the original `swbuff.el` and `swbuff-x.el` have been removed because they are not under source control (and don't seem to be maintained), I guess including it would make sense.

**Comment by manuel-uberti** [comment]
Too kind, thank you. :)

**Comment by joostkremers** [comment]
It's on Melpa. :smiley:

**Comment by manuel-uberti** [comment]
Super, thanks again.
