### ISSUE TITLE
Configure status window height

### ISSUE THREAD

**Issue by manuel-uberti** [joostkremers/nswbuff#2]
Would it be possible to customise the height of the status window? 

Now it looks like this:

![2](https://user-images.githubusercontent.com/8199224/52639114-d818ec80-2ed3-11e9-9771-dd180ba8cbf9.png)

Ideally, I'd like to have it smaller. Something like:

![1](https://user-images.githubusercontent.com/8199224/52639143-eb2bbc80-2ed3-11e9-9d21-9dc54aa57b73.png)

**Comment by joostkremers** [comment]
In the second png, I don't see a status window at all... Is that what you mean?

**Comment by manuel-uberti** [comment]
It's just an example of the ideal height, there is no status window there.

**Comment by manuel-uberti** [comment]
My bad, I should have made it clearer: I'd like the nswbuff status window to have the same height of the Echo area.

**Comment by joostkremers** [comment]
Actually, it's a separate buffer above the echo area. It's just doesn't appear that way because it doesn't have a mode line, but it could have one. (See the option `nswbuff-mode-line-format`.)

So I guess what you'd like is to be able to use the minibuffer for the status info. That sounds like it should be doable. I'll look into it. :smiley:

**Comment by manuel-uberti** [comment]
No worries, and no rush at all. This package is already great :)

**Comment by lerouxrgd** [comment]
Would that mean to have a separate frame with `(minibuffer . nil)`, like in `which-key` for instance ?

**Comment by manuel-uberti** [comment]
Not sure about the frame, I was thinking of a dedicated window.

**Comment by lerouxrgd** [comment]
If my understanding is correct, the problem with a window is that it will always be located above the echo area (the extra blank line at the bottom of the screen).
The idea of using a dedicated frame (with a nil minibuffer) instead is that it could hide this echo area, but I am not sure whether this is a good idea.

Besides, if my understanding of @joostkremers suggestion is correct, maybe it is possible to use something like [minibuffer-line](http://elpa.gnu.org/packages/minibuffer-line.html) to write the status info to the minibuffer window (echo area) directly, and thus have no extra blank line at the bottom of the screen.

**Comment by joostkremers** [comment]
> Besides, if my understanding of @joostkremers suggestion is correct, maybe it is possible to use something like [minibuffer-line](http://elpa.gnu.org/packages/minibuffer-line.html) to write the status info to the minibuffer window (echo area) directly, and thus have no extra blank line at the bottom of the screen.

Yes, that was what I meant. But I see no reason why the display method couldn't be more customisable, in the same way that `which-key` does. The only thing that's keeping me from implementing that is time, or more precisely, the lack thereof. I'd welcome pull requests, though.

I didn't know about `minibuffer-line`. Looks interesting, though I'd first check to see how `which-key` does things.

**Comment by lerouxrgd** [comment]
Actually in `which-key` they simply use `display-buffer-in-side-window` which still have the echo area. I think it's similar to what you do with `split-window` in the end.

So I kind of hacked it by simply using `" *Minibuf-0*"` as an output buffer (that's what they use in `minibuffer-line`) and it works fine.
I'll try to clean it up and make a PR so that you can see it in action.
