### ISSUE TITLE
Ignore hidden files

### ISSUE THREAD

**Issue by alienbogart** [joostkremers/nswbuff#7]
How can nswbuff always ignore hidden files (even if they are included on `nswbuff-projectile-buffer-list`)?

**Comment by joostkremers** [comment]
`projectile` offers several ways to exclude files, can't you use one of those? If not, you'll have to write your own `nswbuff-buffer-list-function`, because `nswbuff-projectile-buffer-list` does not provide the option to exclude buffers. If you know some Elisp, you can use the function `nswbuff-projectile-buffer-list` as a starting point. You may want to use the function `nswbuff-exclude-p`. If you don't know Elisp, let me know, I should be able to whip something up

**Comment by alienbogart** [comment]
Thanks. 

In my experience the only reliable (and simple) way to ignore a file on Projectile is to add it to `.gitignore`, and this is not always optimal because I wish to hide some files while keeping them tracked.

I'm not a programmer, so any help on how such a function might look like is appreciated.

And again, thanks!

**Comment by joostkremers** [comment]
Sorry for the late reply. The following should work:

``` emacs-lisp
(defun my-projectile-buffer-list ()
  "Return the buffers of the current Projectile project.
Hidden files (those whose name start with a dot) are removed.
Added to the list are buffers that are not part of the current
project but that match `nswbuff-include-buffer-regexps'.  If the
current buffer is not part of a project, return nil."
  (if-let ((projectile-buffers (seq-filter (lambda (b)
                                             (not (string= (substring (file-name-base (buffer-file-name b)) 0 1) ".")))
                                           (ignore-errors (projectile-project-buffers)))))
      (dolist (buf (buffer-list) projectile-buffers)
        (if (and (nswbuff-include-p (buffer-name buf))
                 (not (memq buf projectile-buffers)))
            (setq projectile-buffers (append projectile-buffers (list buf)))))))

```
